# Site settings
title: spgingras

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spg.github.io" # the base hostname & protocol for your site
twitter_username: spgingras
github_username:  spg
permalink: /blog/:title

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-39204653-2