# Site settings
title: spgingras
description: > # this means to ignore newlines until "baseurl:"
  Simon-Pierre Gingras's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spg.github.io" # the base hostname & protocol for your site
twitter_username: spgingras
github_username:  spg
permalink: /blog/:title

# Build settings
markdown: kramdown
